#!/usr/bin/env bash
# Snapper - One-Click Production Deployment Script
# Usage: ./deploy.sh [--host HOST] [--port PORT] [--repo URL]
#
# This script handles the full deployment lifecycle:
#   1. Clone or update the repository
#   2. Generate production .env from template
#   3. Build and start Docker containers
#   4. Run database migrations
#   5. Configure Caddy reverse proxy
#   6. Open firewall port
#   7. Verify deployment health

set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────────────
INSTALL_DIR="/opt/snapper"
REPO_URL="https://github.com/jmckinley/snapper.git"
CADDY_CERT_DIR="/etc/caddy/certs"
CADDYFILE="/etc/caddy/Caddyfile"
SNAPPER_PORT="${1:-8443}"  # External HTTPS port
COMPOSE_CMD="docker compose -f docker-compose.yml -f docker-compose.prod.yml"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log()  { echo -e "${BLUE}[snapper]${NC} $1"; }
ok()   { echo -e "${GREEN}[  ok  ]${NC} $1"; }
warn() { echo -e "${YELLOW}[ warn ]${NC} $1"; }
err()  { echo -e "${RED}[error ]${NC} $1" >&2; }

# ─── Preflight Checks ──────────────────────────────────────────────────────
log "Running preflight checks..."

if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root"
    exit 1
fi

for cmd in git docker curl openssl; do
    if ! command -v "$cmd" &>/dev/null; then
        err "Required command not found: $cmd"
        exit 1
    fi
done

if ! docker compose version &>/dev/null; then
    err "Docker Compose plugin not found"
    exit 1
fi

ok "Preflight checks passed"

# ─── Step 1: Clone or Update Repository ────────────────────────────────────
log "Setting up repository at $INSTALL_DIR..."

if [[ -d "$INSTALL_DIR/.git" ]]; then
    log "Repository exists, pulling latest changes..."
    cd "$INSTALL_DIR"
    git pull
    ok "Repository updated"
else
    log "Cloning repository..."
    git clone "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
    ok "Repository cloned"
fi

# ─── Step 2: Generate Production .env ──────────────────────────────────────
log "Configuring environment..."

if [[ -f "$INSTALL_DIR/.env" ]]; then
    warn ".env already exists, keeping existing configuration"
    warn "To regenerate, delete $INSTALL_DIR/.env and re-run this script"
else
    # Detect the server's public IP
    SERVER_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}')
    SECRET_KEY=$(openssl rand -hex 32)

    log "Generating .env for server IP: $SERVER_IP"

    cat > "$INSTALL_DIR/.env" <<ENVEOF
# Snapper Production Environment
# Generated by deploy.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Security
SECRET_KEY=${SECRET_KEY}

# Database & Cache (Docker internal networking)
DATABASE_URL=postgresql+asyncpg://snapper:snapper@postgres:5432/snapper
REDIS_URL=redis://redis:6379/0
CELERY_BROKER_URL=redis://redis:6379/1
CELERY_RESULT_BACKEND=redis://redis:6379/2

# Security settings
DENY_BY_DEFAULT=true
REQUIRE_LOCALHOST_ONLY=false
ALLOWED_ORIGINS=https://${SERVER_IP}:${SNAPPER_PORT}
ALLOWED_HOSTS=${SERVER_IP},localhost,app
CORS_ORIGINS=https://${SERVER_IP}:${SNAPPER_PORT}

# Production mode
DEBUG=false
LOG_LEVEL=INFO
ENVIRONMENT=production

# Notifications (configure as needed)
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
ENVEOF

    chmod 600 "$INSTALL_DIR/.env"
    ok "Production .env generated (SECRET_KEY: ${SECRET_KEY:0:8}...)"
fi

# ─── Step 3: Build and Start Containers ────────────────────────────────────
log "Building and starting containers..."

cd "$INSTALL_DIR"
$COMPOSE_CMD up -d --build

# Wait for postgres and redis to be healthy
log "Waiting for database and cache to be ready..."
$COMPOSE_CMD exec -T postgres sh -c 'until pg_isready -U snapper -d snapper; do sleep 1; done' 2>/dev/null
ok "Containers started"

# ─── Step 4: Run Database Migrations ───────────────────────────────────────
log "Running database migrations..."

$COMPOSE_CMD run --rm app alembic upgrade head
ok "Migrations complete"

# ─── Step 5: Restart App (pick up migrated schema) ─────────────────────────
log "Restarting app container..."

$COMPOSE_CMD up -d
ok "App restarted"

# ─── Step 6: Configure Caddy Reverse Proxy ─────────────────────────────────
log "Configuring Caddy reverse proxy on port $SNAPPER_PORT..."

if [[ ! -f "$CADDYFILE" ]]; then
    warn "Caddyfile not found at $CADDYFILE, skipping Caddy configuration"
    warn "You'll need to manually configure your reverse proxy"
else
    # Check if snapper block already exists
    if grep -q ":${SNAPPER_PORT}" "$CADDYFILE" 2>/dev/null; then
        ok "Caddy already configured for port $SNAPPER_PORT"
    else
        # Generate self-signed cert if none exists
        if [[ ! -f "$CADDY_CERT_DIR/cert.pem" ]]; then
            log "Generating self-signed TLS certificate..."
            mkdir -p "$CADDY_CERT_DIR"
            openssl req -x509 -newkey rsa:4096 -keyout "$CADDY_CERT_DIR/key.pem" \
                -out "$CADDY_CERT_DIR/cert.pem" -days 365 -nodes \
                -subj "/CN=snapper" 2>/dev/null
            ok "Self-signed certificate generated"
        fi

        # Append Snapper block to Caddyfile
        cat >> "$CADDYFILE" <<CADDYEOF

:${SNAPPER_PORT} {
    tls ${CADDY_CERT_DIR}/cert.pem ${CADDY_CERT_DIR}/key.pem
    reverse_proxy localhost:8000
}
CADDYEOF

        caddy reload --config "$CADDYFILE" 2>/dev/null
        ok "Caddy configured and reloaded"
    fi
fi

# ─── Step 7: Open Firewall Port ────────────────────────────────────────────
if command -v ufw &>/dev/null; then
    if ufw status | grep -q "Status: active"; then
        if ! ufw status | grep -q "${SNAPPER_PORT}/tcp"; then
            log "Opening port $SNAPPER_PORT in UFW..."
            ufw allow "${SNAPPER_PORT}/tcp" >/dev/null
            ok "Firewall port $SNAPPER_PORT opened"
        else
            ok "Firewall port $SNAPPER_PORT already open"
        fi
    fi
fi

# ─── Step 8: Verify Deployment ─────────────────────────────────────────────
log "Verifying deployment..."

# Wait for app to be healthy
sleep 5

# Check internal health
if curl -sf http://127.0.0.1:8000/health >/dev/null 2>&1; then
    ok "App health check passed (internal)"
else
    err "App health check failed on localhost:8000"
    log "Check logs with: cd $INSTALL_DIR && $COMPOSE_CMD logs app"
    exit 1
fi

# Check readiness (DB + Redis)
READY=$(curl -sf http://127.0.0.1:8000/health/ready 2>/dev/null || echo '{}')
if echo "$READY" | grep -q '"status":"ready"'; then
    ok "Database and Redis connected"
else
    warn "Readiness check returned: $READY"
fi

# Check external access via Caddy
if curl -skf "https://127.0.0.1:${SNAPPER_PORT}/health" >/dev/null 2>&1; then
    ok "External access via Caddy working"
else
    warn "External HTTPS check failed — Caddy may need configuration"
fi

# ─── Done ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Snapper deployed successfully!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Dashboard:  ${BLUE}https://${SERVER_IP:-localhost}:${SNAPPER_PORT}/${NC}"
echo -e "  API Docs:   ${BLUE}https://${SERVER_IP:-localhost}:${SNAPPER_PORT}/api/docs${NC}"
echo -e "  Health:     ${BLUE}https://${SERVER_IP:-localhost}:${SNAPPER_PORT}/health${NC}"
echo ""
echo -e "  Manage:     cd $INSTALL_DIR"
echo -e "  Logs:       $COMPOSE_CMD logs -f"
echo -e "  Stop:       $COMPOSE_CMD down"
echo -e "  Update:     git pull && $COMPOSE_CMD up -d --build"
echo ""
