"""Add agent version environment trust scoring

Revision ID: 08ffce791cd8
Revises: 002
Create Date: 2026-02-06 01:50:02.396436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ffce791cd8'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('agent_version', sa.String(length=50), nullable=True, comment='Reported agent version (e.g., 2026.1.29)'))
    op.add_column('agents', sa.Column('agent_type', sa.String(length=100), nullable=True, comment='Agent framework type (openclaw, claude-code, cursor, etc.)'))
    op.add_column('agents', sa.Column('execution_environment', sa.String(length=50), nullable=False, server_default='unknown', comment='Reported execution environment for sandbox enforcement'))
    op.add_column('agents', sa.Column('trust_score', sa.Float(), nullable=False, server_default='1.0', comment='Adaptive trust score (0.0-1.0), reduced on violations'))
    op.add_column('agents', sa.Column('auto_adjust_trust', sa.Boolean(), nullable=False, server_default='false', comment='Whether to auto-reduce trust score on denials'))
    op.add_column('agents', sa.Column('violation_count', sa.Integer(), nullable=False, server_default='0', comment='Number of rule violations by this agent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'violation_count')
    op.drop_column('agents', 'auto_adjust_trust')
    op.drop_column('agents', 'trust_score')
    op.drop_column('agents', 'execution_environment')
    op.drop_column('agents', 'agent_type')
    op.drop_column('agents', 'agent_version')
    # ### end Alembic commands ###
