"""Device model for browser extension endpoint tracking."""

import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    String,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class DeviceStatus(str, Enum):
    """Status of a registered device."""

    ACTIVE = "active"
    BLOCKED = "blocked"


class Device(Base):
    """
    Registered browser extension endpoint.

    Devices are auto-registered when an authenticated extension user
    makes their first evaluate request. Admins can block devices to
    immediately deny all traffic from a compromised endpoint.
    """

    __tablename__ = "devices"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Extension-generated persistent UUID
    device_id: Mapped[str] = mapped_column(
        String(36),
        unique=True,
        nullable=False,
        index=True,
        comment="UUID generated by the browser extension",
    )

    # Ownership
    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    organization_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Device info
    name: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="User-assigned label (e.g. John's MacBook)",
    )
    platform: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="navigator.platform (e.g. MacIntel, Win32)",
    )
    browser: Mapped[Optional[str]] = mapped_column(
        String(200),
        nullable=True,
        comment="Parsed from User-Agent header",
    )

    # Status
    status: Mapped[DeviceStatus] = mapped_column(
        String(20),
        default=DeviceStatus.ACTIVE,
        nullable=False,
    )

    # Timestamps
    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Extra metadata (screen, timezone, cores, memory, etc.)
    metadata_json: Mapped[Optional[dict]] = mapped_column(
        "metadata",
        JSONB,
        nullable=True,
        default=None,
    )

    # Relationships
    user: Mapped[Optional["User"]] = relationship("User", lazy="selectin")

    __table_args__ = (
        Index("ix_devices_user_org", "user_id", "organization_id"),
    )

    def __repr__(self) -> str:
        return f"<Device(id={self.id}, device_id={self.device_id}, status={self.status})>"
